version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      HSTS: 'off'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs/self-signed:/etc/nginx/certs:ro
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./conf/nginx-proxy-wordpress.conf:/etc/nginx/vhost.d/location:ro
networks:
  default:
    external:
      name: nginx-proxy
